### ISSUE TITLE
EQ-Simulation:

### ISSUE THREAD

**Issue by MichaelLangbein** [riesgos/riesgos-frontend#10]
- when using expert eq as input, takes very long

**Comment by MichaelLangbein** [comment]
[request.txt](https://github.com/riesgos/riesgos-frontend/files/3519168/request.txt)

**Comment by nbrinckm** [comment]
Is it also that slow using the rz-vm140.gfz-potsdam.de server?

**Comment by MichaelLangbein** [comment]
Nope, works like a charm :) Thanks, closing the issue!
