### ISSUE TITLE
Call DEUS a second time for Tsunami-Service

### ISSUE THREAD

**Issue by MichaelLangbein** [riesgos/riesgos-frontend#12]
- Deus is called multiple times
 - using modelProp's output ('selectedRows', an exposure model), Deus returns a damage-product.
 - using shakygrounds output, Deus updates the damage-product
 - using ts-simulations output, deus updates the damage product again.

**Comment by nbrinckm** [comment]
I'm working on making clear how we can handle the file with loss data (so the loss for each transition from one damage state to another). I'm not sure whether we should allow the user to give us their loss data. Other option would be to provide a set of loss files for the different schemas.
I already sent a mail to Camilo to check his option about that.
