### ISSUE TITLE
Check WMS Output for Shakemaps

### ISSUE THREAD

**Issue by nbrinckm** [riesgos/riesgos-frontend#22]
At the moment the output of the WMS Shakemaps from the GFZ Server looks very different from the one that 52°North provides.

Check two things:
- the spatial extend of the WMS Shakemaps looks wrong (it is often cut on one side)
- check the colors and classes with the USGS conventions (they look way to light blue)

@bpross-52n Would you able to send us the code (and maybe the styling) that you use at the moment on the 52°North WPS?

**Comment by MichaelLangbein** [comment]
![shakyground_output](https://user-images.githubusercontent.com/13807050/63420004-1c96bf00-c406-11e9-9557-a9648a162894.png)

**Comment by bpross-52n** [comment]
Hi, this is the code we use: 
https://github.com/bpross-52n/wps-process-repository-skeleton/blob/feature/python-repository/src/main/java/org/n52/wps/python/util/ShakemapConverter.java

**Comment by bpross-52n** [comment]
This is the SLD:

<?xml version="1.0" encoding="UTF-8"?>

<sld:StyledLayerDescriptor xmlns="http://www.opengis.net/sld" xmlns:sld="http://www.opengis.net/sld" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" version="1.0.0">
  <sld:NamedLayer>
    <sld:Name/>
    <sld:UserStyle>
      <sld:Name>Default Styler</sld:Name>
      <sld:FeatureTypeStyle>
        <sld:Name>name</sld:Name>
        <sld:Rule>
          <sld:RasterSymbolizer>
            <sld:ColorMap>
              <sld:ColorMapEntry color="#6699FF" opacity="0" quantity="0" label=""/>
              <sld:ColorMapEntry color="#6699FF" opacity="1.0" quantity="0.09" label=""/>
              <sld:ColorMapEntry color="#009999" opacity="1.0" quantity="0.16" label=""/>
              <sld:ColorMapEntry color="#009966" opacity="1.0" quantity="0.25" label=""/>
              <sld:ColorMapEntry color="#00CC33" opacity="1.0" quantity="0.36" label=""/>
              <sld:ColorMapEntry color="#71C627" opacity="1.0" quantity="0.5"/>
              <sld:ColorMapEntry color="#CCFF00" opacity="1.0" quantity="0.62" label=""/>
              <sld:ColorMapEntry color="#FFFF00" opacity="1.0" quantity="0.7" label=""/>
              <sld:ColorMapEntry color="#FFCC00" opacity="1.0" quantity="0.81" label=""/>
              <sld:ColorMapEntry color="#FF9900" opacity="1.0" quantity="0.96" label=""/>
              <sld:ColorMapEntry color="#FF0000" opacity="1.0" quantity="1" label=""/>
            </sld:ColorMap>
            <sld:ContrastEnhancement>
              <sld:GammaValue>1.0</sld:GammaValue>
            </sld:ContrastEnhancement>
          </sld:RasterSymbolizer>
        </sld:Rule>
      </sld:FeatureTypeStyle>
    </sld:UserStyle>
  </sld:NamedLayer>
</sld:StyledLayerDescriptor>

**Comment by nbrinckm** [comment]
Thank you very much.

**Comment by nbrinckm** [comment]
@bpross-52n  Is there a parameter that we can give to the GeoserverWMSGenerator to set the default style in the java code?

**Comment by bpross-52n** [comment]
@nbrinckm I don't think the style can be set at the time of import into the Geoserver. The style is set as default for the respective workspace in our Geoserver instance, if that helps..

**Comment by nbrinckm** [comment]
@bpross-52n I have the feeling that I'm way to stupid, but @ruester and me don't find a way the set a style as default for a working space.

**Comment by bpross-52n** [comment]
@nbrinckm I have selected the workspace in this dropdown in the Stil Editor:
![GeoServer_default_style_for_workspace](https://user-images.githubusercontent.com/3692794/63513402-5fc85f00-c4e6-11e9-9e8d-d5eba36d0832.png)

**Comment by nbrinckm** [comment]
@bpross-52n 

We set this style to be part of the N52 workspace, which is the workspace that the wps-4.0.0-beta8 version uses.

![grafik](https://user-images.githubusercontent.com/8684841/63513890-a66a8900-c4e7-11e9-8190-b1a840654747.png)


But this url:

http://rz-vm140.gfz-potsdam.de:80/geoserver/wms?Service=WMS&Request=GetMap&Version=1.1.1&layers=N52:primary1989614240129850017_94f5a.tif&width=191&height=230&format=image/png&bbox=-72.0,-35.0,-69.0,-32.0&srs=EPSG:4326

still gives a black image (so there is the global raster default styling I think).

Only if I add 
```
&styles=shakemap-pga
```
(@MichaelLangbein and by the way this is the name of the style that we want to use)
I get the colored image.

```
http://rz-vm140.gfz-potsdam.de:80/geoserver/wms?Service=WMS&Request=GetMap&Version=1.1.1&layers=N52:primary1989614240129850017_94f5a.tif&width=191&height=230&format=image/png&bbox=-72.0,-35.0,-69.0,-32.0&srs=EPSG:4326&styles=shakemap-pga
```

**Comment by nbrinckm** [comment]
I remember in the docker image I got from you, that there was another version of the wms generator (which also inserted in the riesgos workspace).

Maybe the generator added the style, or it updated the default style for the layer after inserting the tiff.

**Comment by nbrinckm** [comment]
And at least in the wps-js-client (the very old one still from the docker image that I got from you) there is the hardcoded style attribute with the shakemap value.

**Comment by bpross-52n** [comment]
Right... Now that I gave it some thought, I guess we ended up replacing the "raster" style with the shakemap style... Then it should be chosen by default..

**Comment by nbrinckm** [comment]
Ok, this is something that I don't want to do actually.
But since we talked with @MichaelLangbein  and @boeckMt the style can be set within the demonstrator.

The only thing that stays a bit annoying for me, is that the wms output in qgis is still just black, but since we provide wps to get the shakemaps as geotiff we have a much better way for the people to work with the data.

**Comment by bpross-52n** [comment]
Strangely, it seems that QGIS doesn't support setting of styles... I can change the style using ArcMap..
