### ISSUE TITLE
Shakyground: 'Canvas tainted' when WMS is displayed

### ISSUE THREAD

**Issue by MichaelLangbein** [riesgos/riesgos-frontend#40]
When a shakyground-wms result is displayed in the frontend, no popups work anymore. The reason is that the browser refuses to interact with the canvas, because it has been 'tainted' by 3rd party content. 

https://gis.stackexchange.com/questions/199540/avoiding-cors-error-with-openlayers-3 suggests that this can be resolved serverside with correct headers and clientside with the 'crossOrigin' attribute.

**Comment by ruester** [comment]
I have implemented testing solution for this on the server. But the CORS headers are set only if there is the "Origin" header send in the request.
For the demonstrator I can see that RetrieveResultServlet request has this header is set to http://riesgos.dlr.de/ but not for the WMS requests to the GeoServer, like http://rz-vm140.gfz-potsdam.de/geoserver/wms
Is it possible that you can somehow add the "Origin" header to the request made to the WMS endpoint?

![image](https://user-images.githubusercontent.com/1287885/67491141-b5e78900-f674-11e9-8fce-55a2a894df0d.png)

![image](https://user-images.githubusercontent.com/1287885/67491178-c435a500-f674-11e9-8d96-522720281792.png)

**Comment by MichaelLangbein** [comment]
Done! Works like a charm :) App is building right now, should be online in a minute...

**Comment by MichaelLangbein** [comment]
Spiffy! That was awesome work! Closing happily :)
