### ISSUE TITLE
Reliability-Service:

### ISSUE THREAD

**Issue by MichaelLangbein** [riesgos/riesgos-frontend#43]
Throws exception on execution with earthquake.

org.n52.wps.server.ExceptionReport: There is an error on stderr: Traceback (most recent call last): File "System_Reliability_Analysis_local.py", line 157, in <module> main() File "System_Reliability_Analysis_local.py", line 129, in main intensity_provider = shakemap.Shakemaps.from_file(args.intensity_file).to_intensity_provider() File "/usr/share/git/system_reliability/shakemap.py", line 74, in from_file xml = le.parse(file_name) File "src/lxml/etree.pyx", line 3467, in lxml.etree.parse File "src/lxml/parser.pxi", line 1839, in lxml.etree._parseDocument File "src/lxml/parser.pxi", line 1865, in lxml.etree._parseDocumentFromURL File "src/lxml/parser.pxi", line 1769, in lxml.etree._parseDocFromFile File "src/lxml/parser.pxi", line 1163, in lxml.etree._BaseParser._parseDocFromFile File "src/lxml/parser.pxi", line 601, in lxml.etree._ParserContext._handleParseResultDoc File "src/lxml/parser.pxi", line 711, in lxml.etree._handleParseResult Fi

**Comment by sabinehelm** [comment]
Comments from Matthias:
auch hier ist wieder das Problem wegen den großen Shakemap-Dateien, die es seit dem letzten Update von shakyground gibt.
Wir haben dafür auch den deus-Prozess ändern müssen. Ich habe die gleichen Änderungen von deus nun auch mal bei dem System Reliability Source-Code geändert. Ich habe auch gleich noch ein aktuelles Docker-Image gebaut, dass ihr gern nutzen und mit dem alten Image austauschen könnt.

Docker image for system reliability service was updated on the server.
@Michael: please test.

**Comment by MichaelLangbein** [comment]
Works perfectly! Thanks a lot everyone! That's really sweet :)
