### ISSUE TITLE
Chile: System reliability simulation

### ISSUE THREAD

**Issue by MichaelLangbein** [riesgos/riesgos-frontend#5]
Using inputs from TS- and EQ-damge/loss services

Hugo Rosero, Sabine Helm, Michael Langbein

**Comment by ruester** [comment]
Service can now be found at http://rz-vm140.gfz-potsdam.de/wps/WebProcessingService?service=WPS&request=DescribeProcess&version=2.0.0&identifier=org.n52.gfz.riesgos.algorithm.impl.CachedSystemReliabilityProcess
Ideally using the GeoJSON output format and using a styling like https://github.com/ruester/System_Reliability/blob/development-sprint/SLD/SystemReliabilityStyle.sld
This service still needs some clarification on where to get the input and in which format (this will be a later addition for the deus service?).
But for now the example input data https://github.com/HugoRosero/System_Reliability/blob/master/E1_EPN_ExposureNodes_withDamage.geojson will work just fine.

**Comment by nbrinckm** [comment]
It's not the cached one, but rest should ne true.
