### ISSUE TITLE
Styling of earthquakes

### ISSUE THREAD

**Issue by MichaelLangbein** [riesgos/riesgos-frontend#7]
- sld-parser: not equal to display in qgis
- decide on some general, overal styling

**Comment by boeckMt** [comment]
The qgis simple marker size (in px) corresponds to the diameter and the [SLDReader](https://github.com/NieuwlandGeo/SLDReader) library uses the openlayers ol/style/Circle which is setting the radius of the circle, so the size is doubled.

As described in the SLD spec 
> The Size element gives the absolute size of the graphic in pixels encoded as a floatingpoint number.
SLDReader library should convert the incoming size for PointSymbolizer to the radius of ol/style/Circle

**Comment by boeckMt** [comment]
maybe use [mapbox-gl-js](https://docs.mapbox.com/mapbox-gl-js/style-spec/) and not SLD

**Comment by boeckMt** [comment]
[NieuwlandGeo/SLDReader#47](https://github.com/NieuwlandGeo/SLDReader/issues/47) is fixed.
and then size is further divided by 2 for smaller icons
